# Generated by Django 6.0.4 on 2026-04-17 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, verbose_name='Display name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.CreateModel(
            name='UserCollaboratorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='users.collaborator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User collaborator link',
                'verbose_name_plural': 'User collaborator links',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_user_collaborator_link'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('collaborator',), name='uniq_active_collaborator_user_link')],
            },
        ),
    ]
