# Generated by Django 6.0.4 on 2026-04-17 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collaborator_and_user_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Job title'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='professional_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Professional email'),
        ),
        migrations.CreateModel(
            name='CollaboratorDepartmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='users.collaborator')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_links', to='users.department')),
            ],
            options={
                'verbose_name': 'Collaborator department link',
                'verbose_name_plural': 'Collaborator department links',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('collaborator',), name='uniq_active_collaborator_department_link')],
            },
        ),
    ]
