# Generated by Django 6.0.4 on 2026-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='financial_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['cnpj'], name='clients_cli_cnpj_a5fbeb_idx'),
        ),
    ]
