# Generated by Django 6.0.4 on 2026-08-26 18:33

import blackbeans_api.integrations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('rd_station_crm', 'RD Station CRM')], max_length=32, unique=True)),
                ('create_deals', models.BooleanField(default=False)),
                ('pipeline_id', models.CharField(blank=True, default='', max_length=24)),
                ('stage_id', models.CharField(blank=True, default='', max_length=24)),
                ('owner_id', models.CharField(blank=True, default='', max_length=24)),
                ('source_id', models.CharField(blank=True, default='', max_length=24)),
                ('min_score_for_deal', models.PositiveSmallIntegerField(default=0)),
                ('only_contacts_with_email_or_phone', models.BooleanField(default=True)),
                ('cnpj_custom_field_slug', models.CharField(blank=True, default='cnpj', max_length=80)),
                ('legal_bases', models.JSONField(blank=True, default=blackbeans_api.integrations.models.default_legal_bases)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128)),
                ('webhook_header_name', models.CharField(blank=True, default='X-BlackBeans-RD', max_length=64)),
                ('webhook_registered', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration settings',
                'verbose_name_plural': 'Integration settings',
            },
        ),
        migrations.CreateModel(
            name='RdWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_uuid', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], db_index=True, default='received', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RD webhook event',
                'verbose_name_plural': 'RD webhook events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('rd_station_crm', 'RD Station CRM')], max_length=32, unique=True)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration credential',
                'verbose_name_plural': 'Integration credentials',
            },
        ),
        migrations.CreateModel(
            name='RdEntityMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('rd_station_crm', 'RD Station CRM')], db_index=True, default='rd_station_crm', max_length=32)),
                ('local_type', models.CharField(choices=[('company', 'Company'), ('contact', 'Contact'), ('deal', 'Deal')], db_index=True, max_length=16)),
                ('local_id', models.UUIDField(db_index=True)),
                ('remote_type', models.CharField(choices=[('organization', 'Organization'), ('contact', 'Contact'), ('deal', 'Deal')], db_index=True, max_length=16)),
                ('remote_id', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('sync_status', models.CharField(choices=[('syncing', 'Syncing'), ('synced', 'Synced'), ('pending_update', 'Pending update'), ('error', 'Error')], db_index=True, default='syncing', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RD entity mapping',
                'verbose_name_plural': 'RD entity mappings',
                'indexes': [models.Index(fields=['provider', 'sync_status'], name='integration_provide_89796a_idx'), models.Index(fields=['provider', 'local_type', 'sync_status'], name='integration_provide_0cda21_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'local_type', 'local_id'), name='integrations_rdmap_local_uniq'), models.UniqueConstraint(condition=models.Q(('remote_id', ''), _negated=True), fields=('provider', 'remote_type', 'remote_id'), name='integrations_rdmap_remote_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RdSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('select_all_matching', models.BooleanField(default=False)),
                ('force_resync', models.BooleanField(default=False)),
                ('create_deals_snapshot', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rd_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RD sync job',
                'verbose_name_plural': 'RD sync jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('rd_station_crm', 'RD Station CRM')], db_index=True, max_length=32)),
                ('state', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth state',
                'verbose_name_plural': 'OAuth states',
                'indexes': [models.Index(fields=['expires_at'], name='integration_expires_f24735_idx')],
            },
        ),
        migrations.CreateModel(
            name='RdSyncJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integrations.rdsyncjob')),
            ],
            options={
                'verbose_name': 'RD sync job item',
                'verbose_name_plural': 'RD sync job items',
                'constraints': [models.UniqueConstraint(fields=('job', 'company_id'), name='integrations_rdjobitem_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RdSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.rdsyncjob')),
            ],
            options={
                'verbose_name': 'RD sync log',
                'verbose_name_plural': 'RD sync logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'created_at'], name='integration_company_47f170_idx')],
            },
        ),
    ]
