# Generated by Django 6.0.4 on 2026-08-27

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_client_cnpj_client_contact_name_and_more"),
        ("governance", "0034_task_always_in_sprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidMediaConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("meta", "Meta")], default="meta", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_media_connections",
                        to="governance.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paid media connection",
                "verbose_name_plural": "Paid media connections",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "provider"),
                        name="paid_media_connection_workspace_provider_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider", "meta")),
                        name="paid_media_connection_provider_meta",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetaAdAccountLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_account_id", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta_ad_account_links",
                        to="clients.client",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_links",
                        to="paid_media.paidmediaconnection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta_ad_account_links",
                        to="governance.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta ad account link",
                "verbose_name_plural": "Meta ad account links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "external_account_id"),
                        name="paid_media_link_workspace_external_id_uniq",
                    ),
                ],
            },
        ),
    ]

