# Generated by Django 6.0.4 on 2026-08-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_leadcompany_and_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="contact_is_decision_maker",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="contact_is_person",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_is_generic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_is_shared",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_is_shared",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadcompany",
            name="contact_is_decision_maker",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadcompany",
            name="contact_is_person",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadcompany",
            name="email_is_generic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadcompany",
            name="email_is_shared",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="leadcompany",
            name="phone_is_shared",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["contact_is_decision_maker"], name="leads_lead_contact_dm_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["email_is_generic", "phone_is_shared"],
                name="leads_lead_email_ph_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leadcompany",
            index=models.Index(
                fields=["contact_is_decision_maker", "email_is_generic", "phone_is_shared"],
                name="leads_leadc_prospect_idx",
            ),
        ),
    ]
