# Generated by Django 6.0.4 on 2026-04-20 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_portfolio_description_project_actual_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.PositiveIntegerField(default=1)),
                ('wip_limit', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='governance.board')),
            ],
            options={
                'verbose_name': 'Board Group',
                'verbose_name_plural': 'Board Groups',
                'indexes': [models.Index(fields=['board', 'position'], name='governance__board_i_e061f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('board', 'position'), name='uniq_board_group_position')],
            },
        ),
    ]
