# Generated by Django 6.0.4 on 2026-05-26 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_cnpj_client_contact_name_and_more'),
        ('governance', '0008_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emits_invoice', models.BooleanField(default=True)),
                ('has_iss_retention', models.BooleanField(default=False)),
                ('has_inss_retention', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('boleto', 'Boleto'), ('transfer', 'Transfer'), ('pix', 'Pix'), ('other', 'Other')], default='boleto', max_length=24)),
                ('payment_other', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Contract',
                'verbose_name_plural': 'Client Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractServiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('one_off', 'One-off'), ('recurring', 'Recurring')], default='one_off', max_length=16)),
                ('recurrence', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('other', 'Other')], default='', max_length=24)),
                ('recurrence_other', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='governance.clientcontract')),
            ],
            options={
                'verbose_name': 'Contract Service Line',
                'verbose_name_plural': 'Contract Service Lines',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='contract_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='governance.contractserviceline'),
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Catalog',
                'verbose_name_plural': 'Service Catalog',
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='governance__is_acti_4166bd_idx')],
            },
        ),
        migrations.AddField(
            model_name='contractserviceline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='governance.servicecatalog'),
        ),
        migrations.AddIndex(
            model_name='clientcontract',
            index=models.Index(fields=['status', 'created_at'], name='governance__status_9e073b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractserviceline',
            index=models.Index(fields=['service_type', 'recurrence'], name='governance__service_f4065f_idx'),
        ),
    ]
