# Generated by Codex on 2026-05-26

from django.db import migrations


def seed_service_catalog(apps, schema_editor):
    ServiceCatalog = apps.get_model("governance", "ServiceCatalog")
    names = [
        "Desenvolvimento de Site",
        "Hotsite/Pre-Hotsite",
        "Manutencao de Site",
        "Artes Avulsas",
        "Desenvolvimento de Marca",
        "Apresentacao Digital",
        "Marketing Digital/Gerenciamento de Midia",
        "Gerenciamento de Midia",
        "Performance",
        "Planejamento",
        "Social Media",
    ]
    for order, name in enumerate(names, start=1):
        ServiceCatalog.objects.get_or_create(
            name=name,
            defaults={"display_order": order, "description": "", "is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0009_clientcontract_contractserviceline_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_service_catalog, migrations.RunPython.noop),
    ]

