# Generated by Django 6.0.4 on 2026-06-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_notification_celery_beat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='governance__user_id_f87410_idx',
            old_name='governance__user_id_8f1a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdeliverylog',
            new_name='governance__user_id_3c313e_idx',
            old_name='governance__user_id_g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdigestitem',
            new_name='governance__user_id_54d1d2_idx',
            old_name='governance__user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationsubscription',
            new_name='governance__target__378191_idx',
            old_name='governance__target__a1b2c3_idx',
        ),
    ]
