# Generated by Django 6.0.4 on 2026-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0026_task_intake_and_sprint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='governance__agent_i_73919d_idx',
            old_name='governance__agent_i_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='governance__status_791da3_idx',
            old_name='governance__status_8d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='governance__parent__5ef863_idx',
            old_name='governance__parent__8a0f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='taskstatusdefinition',
            new_name='governance__is_acti_9459e6_idx',
            old_name='governance__is_acti_status_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('task_due_soon', 'Task Due Soon'), ('task_commented', 'Task Commented'), ('task_mentioned', 'Task Mentioned'), ('task_status_changed', 'Task Status Changed'), ('task_priority_changed', 'Task Priority Changed'), ('task_updated', 'Task Updated'), ('agent_report', 'Agent Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('task_due_soon', 'Task Due Soon'), ('task_commented', 'Task Commented'), ('task_mentioned', 'Task Mentioned'), ('task_status_changed', 'Task Status Changed'), ('task_priority_changed', 'Task Priority Changed'), ('task_updated', 'Task Updated'), ('agent_report', 'Agent Report')], max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort_points',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6),
        ),
    ]
