# Generated by Django 6.0.4 on 2026-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0027_effort_points_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='effort_points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
