# Generated by Django 6.0.4 on 2026-08-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0028_effort_points_two_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pull_status_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
